#include "Common.ush"

Texture2D GBufferC;
Texture2D ToonOutlineTexture;
SamplerState PointClampSampler;

void MainPS(
    float4 SvPosition : SV_POSITION
    , out float4 OutColor : SV_Target0
    )
{
    float2 UV = SvPositionToBufferUV(SvPosition);
	float3 BaseColor = GBufferC.Sample(PointClampSampler, UV, 0).rgb;
	float Mask = ToonOutlineTexture.Sample(PointClampSampler, UV, 0).r;
	//Mask = smoothstep(0.9,1,Mask);
    OutColor = float4( lerp(0.0f,BaseColor,Mask),0);
}